defaults:
  - override hydra/job_logging: none
  - override hydra/hydra_logging: none

save_dir: /home/jingyan/Documents/csi_sign_language/results
device: cuda

model:
  type: v2
  num_class: 1233
  d_model: 256
  num_node_hand: 21
  num_node_pose: 33
  in_channel: 2

train:
  lr: 1e-4
  epoch: 20
  
data:
  num_class: 1233
  phoenix14_root: /home/jingyan/Documents/csi_sign_language/dataset/phoenix2014-release
  graph_subset_root: /home/jingyan/Documents/csi_sign_language/dataset/graph_subset
  clip_size: 32  #the size to cut video into clips time_length%clip_size == 0
  time_length: 128  #the time length of dimension 
  num_workers: 8
  train_loader:
    batch_size: 2

  validate_loader:
    batch_size: 16

  test_loader:
    batch_size: 16


