save_dir: /home/jingyan/Documents/csi_sign_language/results
device: cuda

model:
  d_model: 2048
  num_node: 21
  in_channel: 2
  num_encoder: 2

train:
  lr: 1e-4
  epoch: 20
  
data:
  num_class: 3695
  phoenix14_root: /home/jingyan/Documents/csi_sign_language/dataset/phoenix2014-release
  graph_subset_root: /home/jingyan/Documents/csi_sign_language/dataset/graph_subset
  clip_size: 64  #the size to cut video into clips time_length%clip_size == 0
  time_length: 128  #the time length of dimension 
  num_workers: 8
  train_loader:
    batch_size: 4

  validate_loader:
    batch_size: 16

  test_loader:
    batch_size: 16


